apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

configMapGenerator:
  - name: zammad-access-gate-templates
    files:
      - templates/error.html
      - templates/robots.txt

generatorOptions:
  disableNameSuffixHash: true