apiVersion: v1
kind: Service
metadata:
  name: zammad-access-gate
  labels:
    app: zammad-access-gate
    app.kubernetes.io/name: zammad-access-gate
    app.kubernetes.io/component: access-gate
spec:
  type: ClusterIP
  selector:
    app: zammad-access-gate
  ports:
    - name: http
      port: 4180
      targetPort: http
      protocol: TCP