apiVersion: apps/v1
kind: Deployment
metadata:
  name: zammad-access-gate
spec:
  template:
    spec:
      containers:
        - name: oauth2-proxy
          env:
            - name: OIDC_ISSUER_URL
              value: https://aai-dev.egi.eu/auth/realms/egi
            - name: REDIRECT_URL
              value: https://zammad-echoes-helpdesk-staging.apps.bst2.paas.psnc.pl/oauth2/callback